### ISSUE TITLE
example credentials

### ISSUE THREAD

**Issue by ghost** [peihsinsu/google-vision-api-client#1]
tell me about code/example inside itri-smart-home-33f5a755a360.json ?. thanks

**Comment by peihsinsu** [comment]
Hi Emaknyus

The json file is the service account json file that create from the vision api enabled project.
You can create service account from "https://console.cloud.google.com/permissions/serviceaccounts?project=[your-project-id]".
Hope this helps.

Best Wish,
Send by Simon Su

**Comment by ghost** [comment]
okay, thank you.
